### ISSUE TITLE
undefined method `git_recurse'

### ISSUE THREAD

**Issue by leoarnold** [markdownlint/markdownlint#120]
I got

``` text
$ bundle exec mdl --style .mdlstyle.rb
.mdlstyle.rb:1:in `load': undefined method `git_recurse' for #<MarkdownLint::Style:0x00000002d3e648> (NoMethodError)
```

with 

``` Ruby
git_recurse true
```

using the Gem `mdl (0.2.1)`.

**Comment by mivok** [comment]
The problem you are coming across is due to style files and configuration files doing two different things. Style files are intended to configure the rules used and options related to markdown styles (e.g. line length, list item style and so on). On the other hand, the user configuration file, .mdlrc, is intended to configure user facing options such as git_recurse, or disabling specific rules.

It seems that there is a fair amount of confusion around the difference between style files and configuration files, and I'll be looking at the possibility of merging the two somehow so you can use a single file both for user preferences and markdown style choices.

For more information on what goes in each file currently, see https://github.com/mivok/markdownlint/blob/master/docs/configuration.md and https://github.com/mivok/markdownlint/blob/master/docs/creating_styles.md for the .mdlrc and style file respectively.

In your case, you can add the git_recurse option to a .mdlrc file, and keep your rule options in the style file.

**Comment by mivok** [comment]
I've opened #124 to address the .mdlrc/style file difference mentioned above.
