### ISSUE TITLE
Rationale for MD029?

### ISSUE THREAD

**Issue by SeanKilleen** [markdownlint/markdownlint#392]
## Describe the Enhancement:

I'm attempting to understand the reason for MD029, and to be able to better explain it to others.

### Impacted Rules:

MD029

## Describe the Need:

I am helping some codebases lint their docs for markdown. One question that has come up a few times is why there is a benefit of adopting the `one` style for OLs (e.g. every item beginning with 1).

My understanding is that this is simply to help consistency and the order of things should a numbered item be moved around, but is there more of a rationale beyond that? 

If someone can help validate what I'm saying or link to supporting text, I'd be happy to add it to the rules list via PR.

**Comment by jaymzh** [comment]
Well, the design of OLs is that you don't number them yourself, you just denote it's ordered and what system it uses (123, abc). Just like in HTML, where every item is still just `li`, in MD, they're just `1.`. This is consistent.

If you order them yourselves, any refactor will be error-prone. Any change, or merge (you _are_ maintaining your MD files in some sort of SCM system, right? :) ), is likely to break the ordering and you'll get "1, 2, 4, 5, 5, 7" kinda stuff.

Most lint rules aren't about something being fundamentally wrong, but about enforcing paths that are less-error prone and easier to maintain. MDL - and MD029 in particular - are no exception.

I hope that helps. Feel free to re-open otherwise.

**Comment by SeanKilleen** [comment]
@jaymzh thanks for the succinct explanation! I agree; just wanted to make sure there wasn't more to it.

**Comment by DavidAnson** [comment]
Agree with everything @jaymzh said, however ironically when using a linter I prefer the 1/2/3 style because it's clearer for folks reading the raw text (and the linter will call out any errors).
