### ISSUE TITLE
MD024: property allow_different_nesting is not allowed

### ISSUE THREAD

**Issue by jakoch** [markdownlint/markdownlint#490]
When i click `Edit in settings.json` in the Settings tab of VSCode,
iI'm getting a warning that the usage of the `Property allow_different_nesting is not allowed.`.
How to fix this?

Referencing: [Rules - MD024](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md024---multiple-headers-with-the-same-content), [Source](https://github.com/markdownlint/markdownlint/blob/41fc308f0d7f2647f0ae2c2d3826f48e42d964f4/lib/mdl/rules.rb#L385)

![image](https://github.com/markdownlint/markdownlint/assets/85608/0e2dd43a-d9b0-4cac-a22a-2e3e330df388)

**Comment by DavidAnson** [comment]
It looks like you are using the vscode-markdownlint extension based on the Node implementation of markdownlint (this project is the Ruby implementation). The parameter in question was removed in a recent release of that library because it duplicated another: https://github.com/DavidAnson/markdownlint/commit/f2725178b1e83b07d7f7cc2db64d42f6aa14b8a1

**Comment by jakoch** [comment]
Thank you for the quick response!
I replaced `allow_different_nesting` with `siblings_only` and it works now.
Sorry for reporting to the wrong repo. 
Closing.
